// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rectangle.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestRectangle struct {
	Width                float32  `protobuf:"fixed32,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               float32  `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestRectangle) Reset()         { *m = RequestRectangle{} }
func (m *RequestRectangle) String() string { return proto.CompactTextString(m) }
func (*RequestRectangle) ProtoMessage()    {}
func (*RequestRectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b2054555d417c4, []int{0}
}

func (m *RequestRectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestRectangle.Unmarshal(m, b)
}
func (m *RequestRectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestRectangle.Marshal(b, m, deterministic)
}
func (m *RequestRectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestRectangle.Merge(m, src)
}
func (m *RequestRectangle) XXX_Size() int {
	return xxx_messageInfo_RequestRectangle.Size(m)
}
func (m *RequestRectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestRectangle.DiscardUnknown(m)
}

var xxx_messageInfo_RequestRectangle proto.InternalMessageInfo

func (m *RequestRectangle) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *RequestRectangle) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ResponseRectangleArea struct {
	Area                 float32  `protobuf:"fixed32,1,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseRectangleArea) Reset()         { *m = ResponseRectangleArea{} }
func (m *ResponseRectangleArea) String() string { return proto.CompactTextString(m) }
func (*ResponseRectangleArea) ProtoMessage()    {}
func (*ResponseRectangleArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b2054555d417c4, []int{1}
}

func (m *ResponseRectangleArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseRectangleArea.Unmarshal(m, b)
}
func (m *ResponseRectangleArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseRectangleArea.Marshal(b, m, deterministic)
}
func (m *ResponseRectangleArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseRectangleArea.Merge(m, src)
}
func (m *ResponseRectangleArea) XXX_Size() int {
	return xxx_messageInfo_ResponseRectangleArea.Size(m)
}
func (m *ResponseRectangleArea) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseRectangleArea.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseRectangleArea proto.InternalMessageInfo

func (m *ResponseRectangleArea) GetArea() float32 {
	if m != nil {
		return m.Area
	}
	return 0
}

type ResponseRectanglePerimeter struct {
	Perimeter            float32  `protobuf:"fixed32,1,opt,name=perimeter,proto3" json:"perimeter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseRectanglePerimeter) Reset()         { *m = ResponseRectanglePerimeter{} }
func (m *ResponseRectanglePerimeter) String() string { return proto.CompactTextString(m) }
func (*ResponseRectanglePerimeter) ProtoMessage()    {}
func (*ResponseRectanglePerimeter) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b2054555d417c4, []int{2}
}

func (m *ResponseRectanglePerimeter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseRectanglePerimeter.Unmarshal(m, b)
}
func (m *ResponseRectanglePerimeter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseRectanglePerimeter.Marshal(b, m, deterministic)
}
func (m *ResponseRectanglePerimeter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseRectanglePerimeter.Merge(m, src)
}
func (m *ResponseRectanglePerimeter) XXX_Size() int {
	return xxx_messageInfo_ResponseRectanglePerimeter.Size(m)
}
func (m *ResponseRectanglePerimeter) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseRectanglePerimeter.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseRectanglePerimeter proto.InternalMessageInfo

func (m *ResponseRectanglePerimeter) GetPerimeter() float32 {
	if m != nil {
		return m.Perimeter
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestRectangle)(nil), "proto.requestRectangle")
	proto.RegisterType((*ResponseRectangleArea)(nil), "proto.responseRectangleArea")
	proto.RegisterType((*ResponseRectanglePerimeter)(nil), "proto.responseRectanglePerimeter")
}

func init() { proto.RegisterFile("rectangle.proto", fileDescriptor_17b2054555d417c4) }

var fileDescriptor_17b2054555d417c4 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0xe5, 0x88, 0x56, 0x62, 0x36, 0x04, 0x8b, 0x94, 0x2a, 0x64, 0x51, 0xbc, 0x42, 0x45,
	0x6a, 0x24, 0xd8, 0x65, 0x05, 0x37, 0x40, 0xe5, 0x04, 0x26, 0x8c, 0x1c, 0x4b, 0xc1, 0x0e, 0x63,
	0x53, 0xf6, 0x5c, 0x81, 0xa3, 0x71, 0x05, 0x6e, 0xc0, 0x05, 0x10, 0x4e, 0xea, 0x52, 0x68, 0x57,
	0xf6, 0x8c, 0xe7, 0xcf, 0xfb, 0xdf, 0x70, 0x44, 0x58, 0x7b, 0x69, 0x54, 0x8b, 0x8b, 0x8e, 0xac,
	0xb7, 0x7c, 0x14, 0x8e, 0xbc, 0x50, 0xd6, 0xaa, 0x16, 0x4b, 0xd9, 0xe9, 0x52, 0x1a, 0x63, 0xbd,
	0xf4, 0xda, 0x1a, 0xd7, 0x0f, 0x89, 0x1b, 0x48, 0x09, 0x9f, 0x5f, 0xd0, 0xf9, 0xe5, 0x5a, 0xce,
	0x4f, 0x60, 0xf4, 0xaa, 0x1f, 0x7d, 0x33, 0x65, 0x33, 0x76, 0x91, 0x2c, 0xfb, 0x82, 0x4f, 0x60,
	0xdc, 0xa0, 0x56, 0x8d, 0x9f, 0x26, 0xa1, 0x3d, 0x54, 0xe2, 0x12, 0x32, 0x42, 0xd7, 0x59, 0xe3,
	0x30, 0xae, 0xb8, 0x25, 0x94, 0x9c, 0xc3, 0x81, 0x24, 0x94, 0xc3, 0x96, 0x70, 0x17, 0x15, 0xe4,
	0xff, 0x86, 0xef, 0x90, 0xf4, 0x13, 0x7a, 0x24, 0x5e, 0xc0, 0x61, 0xb7, 0x2e, 0x06, 0xd9, 0xa6,
	0x71, 0xf5, 0xc5, 0x20, 0x8d, 0xa2, 0x7b, 0xa4, 0x95, 0xae, 0x91, 0x2b, 0x38, 0xae, 0x65, 0x5b,
	0x6f, 0x93, 0x4f, 0xfb, 0x70, 0x8b, 0xbf, 0xc9, 0xf2, 0x22, 0x3e, 0xec, 0x30, 0x2c, 0xce, 0xde,
	0x3e, 0x3e, 0xdf, 0x93, 0x4c, 0xa4, 0x65, 0xfc, 0x4a, 0x57, 0xfe, 0xd8, 0xae, 0xd8, 0x9c, 0xaf,
	0x60, 0xb2, 0x05, 0xda, 0xb8, 0xde, 0x4b, 0x3b, 0xdf, 0x47, 0x8b, 0x5a, 0x31, 0x0b, 0xc8, 0x5c,
	0x64, 0xbf, 0x91, 0x31, 0x72, 0xc5, 0xe6, 0x0f, 0xe3, 0xb0, 0xe3, 0xfa, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xc9, 0xa2, 0x4e, 0xef, 0xdf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RectangleServiceClient is the client API for RectangleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RectangleServiceClient interface {
	CalcRectangleArea(ctx context.Context, in *RequestRectangle, opts ...grpc.CallOption) (*ResponseRectangleArea, error)
	CalcRectanglePerimeter(ctx context.Context, in *RequestRectangle, opts ...grpc.CallOption) (*ResponseRectanglePerimeter, error)
}

type rectangleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRectangleServiceClient(cc *grpc.ClientConn) RectangleServiceClient {
	return &rectangleServiceClient{cc}
}

func (c *rectangleServiceClient) CalcRectangleArea(ctx context.Context, in *RequestRectangle, opts ...grpc.CallOption) (*ResponseRectangleArea, error) {
	out := new(ResponseRectangleArea)
	err := c.cc.Invoke(ctx, "/proto.RectangleService/calcRectangleArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rectangleServiceClient) CalcRectanglePerimeter(ctx context.Context, in *RequestRectangle, opts ...grpc.CallOption) (*ResponseRectanglePerimeter, error) {
	out := new(ResponseRectanglePerimeter)
	err := c.cc.Invoke(ctx, "/proto.RectangleService/calcRectanglePerimeter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RectangleServiceServer is the server API for RectangleService service.
type RectangleServiceServer interface {
	CalcRectangleArea(context.Context, *RequestRectangle) (*ResponseRectangleArea, error)
	CalcRectanglePerimeter(context.Context, *RequestRectangle) (*ResponseRectanglePerimeter, error)
}

// UnimplementedRectangleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRectangleServiceServer struct {
}

func (*UnimplementedRectangleServiceServer) CalcRectangleArea(ctx context.Context, req *RequestRectangle) (*ResponseRectangleArea, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcRectangleArea not implemented")
}
func (*UnimplementedRectangleServiceServer) CalcRectanglePerimeter(ctx context.Context, req *RequestRectangle) (*ResponseRectanglePerimeter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcRectanglePerimeter not implemented")
}

func RegisterRectangleServiceServer(s *grpc.Server, srv RectangleServiceServer) {
	s.RegisterService(&_RectangleService_serviceDesc, srv)
}

func _RectangleService_CalcRectangleArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRectangle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RectangleServiceServer).CalcRectangleArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RectangleService/CalcRectangleArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RectangleServiceServer).CalcRectangleArea(ctx, req.(*RequestRectangle))
	}
	return interceptor(ctx, in, info, handler)
}

func _RectangleService_CalcRectanglePerimeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRectangle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RectangleServiceServer).CalcRectanglePerimeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RectangleService/CalcRectanglePerimeter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RectangleServiceServer).CalcRectanglePerimeter(ctx, req.(*RequestRectangle))
	}
	return interceptor(ctx, in, info, handler)
}

var _RectangleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RectangleService",
	HandlerType: (*RectangleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "calcRectangleArea",
			Handler:    _RectangleService_CalcRectangleArea_Handler,
		},
		{
			MethodName: "calcRectanglePerimeter",
			Handler:    _RectangleService_CalcRectanglePerimeter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rectangle.proto",
}
